steps:
# Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/galeria-ai-video-quality-tool:$COMMIT_SHA'
    - '.'

# Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/galeria-ai-video-quality-tool:$COMMIT_SHA''

# Image Deployment to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'galeria-video-moderator-svc'
    - '--image'
    - 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/galeria-ai-video-quality-tool:$COMMIT_SHA'
    - '--platform'
    - 'managed'
    - '--region'
    - 'europe-west1'
    - '--service-account'
    - 'video-moderator-galeria-retail@galeria-retail-api-dev.iam.gserviceaccount.com' 
    - '--no-allow-unauthenticated' 

options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/galeria-ai-video-quality-tool:$COMMIT_SHA'