-- Run this query in your `galeria-retail-api-dev` project's
-- BigQuery SQL Workspace to create or replace the master table.

CREATE OR REPLACE TABLE `galeria-retail-api-dev.moving_images.overview` (
  
  # Core identifier, e.g., "123_01.png"
  image_id STRING,
  
  # Extracted GTIN, e.g., "123"
  gtin STRING,
  
  # Full path to the original image, e.g., "gs://..."
  source_gcs_path STRING,
  
  # The current state of this item in the workflow
  # e.g., PENDING, GENERATING, COMPLETED, MODERATED
  generation_status STRING,
  
  # Counter for generation attempts
  generation_attempts INT64,
  
  # The prompt used for generation (editable)
  prompt STRING,
  
  # The GCS path to the generated .mp4 (no gs:// prefix)
  # e.g., "output_videos/models/123_01.mp4"
  video_id STRING,
  
  # The moderator's final decision
  # e.g., approve, regenerate, remove
  decision STRING,
  
  # Text notes from the moderator
  notes STRING,
  
  # The name of the moderator who made the decision
  moderator_id STRING,
  
  # Timestamp of when the decision was logged
  log_timestamp TIMESTAMP,
  
  # Timestamp of the last time this row was touched
  last_updated TIMESTAMP
);