steps:
# 1. Build the Docker image
# MODIFIED: Pointing to the internal copy of the docker builder
- name: 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/docker'
  args:
  - 'build'
  - '-t'
  - 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/video-moderation-tool:$SHORT_SHA'
  - '.'

# 2. Push the image to Artifact Registry
# MODIFIED: Pointing to the internal copy of the docker builder
- name: 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/docker'
  args:
  - 'push'
  - 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/video-moderation-tool:$SHORT_SHA'

# 3. Deploy to Cloud Run
# MODIFIED: Pointing to the internal copy of the gcloud builder
- name: 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/gcloud'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'video-moderation-tool' # The name of your Cloud Run service
  - '--image=europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/video-moderation-tool:$SHORT_SHA'
  - '--region=europe-west1'
  - '--platform=managed'
  - '--allow-unauthenticated'

images:
- 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/video-moderation-tool:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY