steps:
# Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/galeria-ai-video-quality-tool:$COMMIT_SHA'
    - '.'

# Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/galeria-ai-video-quality-tool:$COMMIT_SHA'

# Image Deployment to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'galeria-video-moderator-svc'
    - '--image'
    - 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/galeria-ai-video-quality-tool:$COMMIT_SHA'
    - '--platform'
    - 'managed'
    - '--region'
    - 'europe-west1'
    - '--service-account'
    - 'video-moderator-galeria-retail@galeria-retail-api-dev.iam.gserviceaccount.com'
    - --mount
    - type=secret,source=video-moderator-key,target=/secrets,mode=0444
    - - --update-env-vars
    - STREAMLIT_SERVER_PORT=8080,GOOGLE_APPLICATION_CREDENTIALS=/secrets/video-moderator-key.json


    
options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'europe-docker.pkg.dev/$PROJECT_ID/galeria-repo/galeria-ai-video-quality-tool:$COMMIT_SHA'
