steps:
  - id: create-terraform-state-bucket
    name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil ls -b 'gs://terraform-${PROJECT_ID}' || gsutil mb -l EU 'gs://terraform-${PROJECT_ID}'

    waitFor: [ '-' ]

  - id: generate-terraform-backend
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - '-c'
      - |
        echo -e "bucket = \"terraform-${PROJECT_ID}\"" > /workspace/config.gcs.tfbackend
        echo -e "prefix = \"video-generation-pipeline\"" > /workspace/config.gcs.tfbackend
        echo "generated backend configuration:"
        cat /workspace/config.gcs.tfbackend

    waitFor: [ '-' ]

  - id: initialize-terraform
    name: hashicorp/terraform:1.14.0
    entrypoint: terraform
    dir: video-generating-pipeline/terraform
    args: [ 'init', '-backend-config=/workspace/config.gcs.tfbackend' ]
    waitFor: [ 'create-terraform-state-bucket', 'generate-terraform-backend' ]

  - id: apply-terraform
    name: hashicorp/terraform:1.14.0
    entrypoint: terraform
    dir: video-generating-pipeline/terraform
    args: [
      'apply',
      '-auto-approve',
      '-var=project_id=${PROJECT_ID}'
    ]

    waitFor: [ 'initialize-terraform' ]

logsBucket: 'gs://terraform-${PROJECT_ID}/logs'
options:
  logging: GCS_ONLY